services:
  - type: web
    name: findly-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/auth/me
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: CORS_ALLOWED_ORIGIN
        value: https://gnu-findly-portal.netlify.app
